export const KeyOptions = [
  "0) 数字键0:Num0",
  "1! 数字键1:Num1",
  "2@ 数字键2:Num2",
  "3# 数字键3:Num3",
  "4$ 数字键4:Num4",
  "5% 数字键5:Num5",
  "6^ 数字键6:Num6",
  "7& 数字键7:Num7",
  "8* 数字键8:Num8",
  "9( 数字键9:Num9",
  "[小键盘]数字键0:Numpad0",
  "[小键盘]数字键1:Numpad1",
  "[小键盘]数字键2:Numpad2",
  "[小键盘]数字键3:Numpad3",
  "[小键盘]数字键4:Numpad4",
  "[小键盘]数字键5:Numpad5",
  "[小键盘]数字键6:Numpad6",
  "[小键盘]数字键7:Numpad7",
  "[小键盘]数字键8:Numpad8",
  "[小键盘]数字键9:Numpad9",
  "字母键A:A",
  "字母键B:B",
  "字母键C:C",
  "字母键D:D",
  "字母键E:E",
  "字母键F:F",
  "字母键G:G",
  "字母键H:H",
  "字母键I:I",
  "字母键J:J",
  "字母键K:K",
  "字母键L:L",
  "字母键M:M",
  "字母键N:N",
  "字母键O:O",
  "字母键P:P",
  "字母键Q:Q",
  "字母键R:R",
  "字母键S:S",
  "字母键T:T",
  "字母键U:U",
  "字母键V:V",
  "字母键W:W",
  "字母键X:X",
  "字母键Y:Y",
  "字母键Z:Z",
  "F1键:F1",
  "F2键:F2",
  "F3键:F3",
  "F4键:F4",
  "F5键:F5",
  "F6键:F6",
  "F7键:F7",
  "F8键:F8",
  "F9键:F9",
  "F10键:F10",
  "F11键:F11",
  "F12键:F12",
  "←Backspace退格键:Backspace",
  "Tab制表键:Tab",
  "Return回车键:Return",
  "↑Shift键(左):LShift",
  "↑Shift键(右):RShift",
  "Ctrl键:Control",
  "Alt键:Alt",
  "Pause键:Pause",
  "CapsLock大写锁定键:CapsLock",
  "Esc键:Escape",
  "空格键:Space",
  "Page Up键:PageUp",
  "Page Down键:PageDown",
  "End键:End",
  "Home键:Home",
  "←左箭头键:LeftArrow",
  "↑上箭头键:UpArrow",
  "→右箭头键:RightArrow",
  "↓下箭头键:DownArrow",
  "Insert键:Insert",
  "Delete删除键:Delete",
  "Windows键:Windows",
  "ContextMenu右键菜单键:ContextMenu",
  "NumLock数字锁定键:NumLock",
  "ScrollLock滚动锁定键:ScrollLock",
  "; ：分号冒号键:OEM1",
  "/ ? 斜杠问号键:OEM2",
  "` ~ 反引号波浪号键:OEM3",
  "[ { 左(中括号花括号键):OEM4",
  "\\ | 反斜杠竖线键:OEM5",
  "] } 右(中括号花括号键):OEM6",
  "' \" 单引号双引号键:OEM7",
  "= + 等于加号键:OEMPlus",
  ", < 逗号小于号键:OEMComma",
  ". > 句号大于号键:OEMPeriod",
  "/ 斜杠键:Divide",
  "* 乘号键:Multiply",
  ". 小数点Del键:Decimal",
  "+ 加号键:Add",
  "- 减号键:Subtract",
  "- _减号下划线键:OEMMinus",
];