export const dialogOptions = <TestModuleDialogType>{
  title: "写入文件",
  targetMethodName: "writeFile",
  content: "将文本写入文件",
  args: [
    {
      componentType: "fileInput",
      value: "",
      suffix: "",
      verifyPath: false,
      desc: "单文件选择",
      id: "Zo8IIjWeA8CmiSbEohXVf",
      onlyTest: false,
      noTest: false,
      name: "path",
      label: "文件路径",
      displayCondition: [],
      placeholder: "请输入文件路径",
      multiple: false,
    },
    {
      componentType: "input",
      value: "",
      desc: "文本输入框",
      id: "f8BMJ7N3b4yLqZdaMxf3z",
      onlyTest: false,
      noTest: false,
      name: "content",
      label: "内容",
      displayCondition: [],
      placeholder: "请输入需要写入文件的内容",
    },
  ],
};
