export const dialogOptions = <TestModuleDialogType>{
  title: "路径解析",
  targetMethodName: "resolve",
  content: "将路径或路径段序列解析为绝对路径",
  args: [
    {
      componentType: "FileInput",
      value: "",
      suffix: "",
      verifyPath: false,
      desc: "单文件选择",
      id: "kE_KrfyUN0QJKVHvVTVEO",
      onlyTest: false,
      noTest: false,
      name: "path",
      label: "主路径",
      displayCondition: [],
      placeholder: "请输入主路径",
      multiple: false,
    },
    {
      componentType: "input",
      value: "",
      desc: "文本输入框",
      id: "eF9D6-lIMLxsh5g4GuoBd",
      onlyTest: false,
      noTest: false,
      name: "addPath",
      label: "路径表达式",
      displayCondition: [],
      placeholder: "请输入路径表达式：如../a.png",
    },
  ],
};
