export const apiDocument = <ApiDocumentType>{
  howToUse: "构建与用户交互的表单",
  params: [
    {
      name: "buildFormList",
      required: false,
      instructions: "表单组件数组",
      type: "BuildFormItems[]",
      default: "[]",
      children: [
        {
          name: "BuildFormItems",
          required: false,
          instructions: "表单组件",
          type: [
            "BuildFormItem.Input",
            "BuildFormItem.Select",
            "BuildFormItem.Check",
            "BuildFormItem.Picker",
          ],
          default: " ",
          children: [
            {
              name: "BuildFormItem.Input",
              required: false,
              instructions: "输入框组件",
              type: [
                "TextInputItem",
                "NumberInputItem",
                "RangeInputItem",
                "DirInputItem",
                "FileInputItem<true>",
                "FileInputItem<false>",
              ],
              default: "",
              children: [
                {
                  name: "TextInputItem",
                  required: false,
                  instructions: "文本输入框",
                  type: "object",
                  default: " ",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "输入的值",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: false,
                      instructions: "输入框类型",
                      type: '"text"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "mod",
                      required: false,
                      instructions: "输入框模式",
                      type: '"password" | "textarea" | "text"',
                      default: "text",
                      children: [],
                    },
                    {
                      name: "placeholder",
                      required: false,
                      instructions: "占位符",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "clearable",
                      required: false,
                      instructions: "是否可清空",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "showPassword",
                      required: false,
                      instructions: "是否显示密码(mod为password时生效)",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "maxlength",
                      required: false,
                      instructions: "最大长度",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "showWordLimit",
                      required: false,
                      instructions: "是否显示字数统计",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "autosize",
                      required: false,
                      instructions: "自适应内容高度(mod为textarea时生效)",
                      type: "[number | undefined, number | undefined] | number | boolean",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "NumberInputItem",
                  required: false,
                  instructions: "数字输入框",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "输入的值",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: true,
                      instructions: "输入框类型",
                      type: '"number"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "min",
                      required: false,
                      instructions: "最小值",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "max",
                      required: false,
                      instructions: "最大值",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "step",
                      required: false,
                      instructions: "步长",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "stepStrictly",
                      required: false,
                      instructions: "是否严格步长",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "precision",
                      required: false,
                      instructions: "精度",
                      type: "number",
                      default: "",
                      children: [],
                    },
                    {
                      name: "controlsPosition",
                      required: false,
                      instructions: "控制按钮位置",
                      type: '"right" | ""',
                      default: "",
                      children: [],
                    },
                    {
                      name: "controls",
                      required: false,
                      instructions: "是否显示控制按钮",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "valueOnClear",
                      required: false,
                      instructions: "清空后的值",
                      type: "number | 'max' | 'min'",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "RangeInputItem",
                  required: false,
                  instructions: "范围输入框",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "范围值",
                      type: "[number, number]",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: true,
                      instructions: "输入框类型",
                      type: '"range"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "limit",
                      required: false,
                      instructions: "范围限制",
                      type: "[number, number]",
                      default: "",
                      children: [],
                    },
                    {
                      name: "controls",
                      required: false,
                      instructions: "是否显示控制按钮",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "DirInputItem",
                  required: false,
                  instructions: "文件夹选择",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "所选文件夹",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: true,
                      instructions: "输入框类型",
                      type: '"dir"',
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "FileInputItem<true>",
                  required: false,
                  instructions: "多文件选择",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "所选文件",
                      type: "string[]",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: true,
                      instructions: "输入框类型",
                      type: '"file"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "multiple",
                      required: true,
                      instructions: "是否多选",
                      type: "true",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "FileInputItem<false>",
                  required: false,
                  instructions: "单文件选择",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Input | "input"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "所选文件",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "inputType",
                      required: true,
                      instructions: "输入框类型",
                      type: '"file"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "multiple",
                      required: true,
                      instructions: "是否多选",
                      type: "false",
                      default: "",
                      children: [],
                    },
                  ],
                },
              ],
            },
            {
              name: "BuildFormItem.Select",
              required: false,
              type: ["BaseSelectItems", "SegmentedItems"],
              instructions: "选择框组件",
              default: "",
              children: [
                {
                  name: "SegmentedItems",
                  required: false,
                  instructions: "分段选择框",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Select | "select"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "选中的值",
                      type: "string | number | boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "segmented",
                      required: true,
                      instructions: "是否分段",
                      type: "true",
                      default: "",
                      children: [],
                    },
                    {
                      name: "multiple",
                      required: true,
                      instructions: "多选",
                      type: "false | undefined",
                      default: "",
                      children: [],
                    },
                    {
                      name: "options",
                      required: true,
                      instructions: "选项",
                      type: "SegmentedOption<T>[]",
                      default: "",
                      children: [
                        {
                          name: "SegmentedOption<T>",
                          required: false,
                          instructions: "分段选项,T为string | number | boolean",
                          type: "object",
                          default: "",
                          children: [
                            {
                              name: "label",
                              required: true,
                              instructions: "选项标签",
                              type: "string",
                              default: "",
                              children: [],
                            },
                            {
                              name: "value",
                              required: true,
                              instructions: "选项值",
                              type: "T",
                              default: "",
                              children: [],
                            },
                            {
                              name: "disabled",
                              required: false,
                              instructions: "是否禁用",
                              type: "boolean",
                              default: "",
                              children: [],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  name: "BaseSelectItems",
                  required: false,
                  type: [
                    "SelectType.Default<T>",
                    "SelectType.Base<T, SelectType.ConstantOption<T>, SelectType.Multiple<T>>",
                    "SelectType.Base<T, SelectType.GroupOption<T>, SelectType.Single<T>>",
                    "SelectType.Base<T, SelectType.GroupOption<T>, SelectType.Multiple<T>>",
                  ],
                  instructions: "基础选择框",
                  default: "",
                  children: [
                    {
                      name: "SelectType.Default<T>",
                      required: false,
                      instructions: "单选基本选项",
                      type: "object",
                      default: "",
                      children: [
                        {
                          name: "type",
                          type: 'FieldType.Select | "select"',
                          required: true,
                          instructions: "组件类型",
                          default: "",
                          children: [],
                        },
                        {
                          name: "id",
                          required: false,
                          instructions: "唯一标识",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "targetGroupLabel",
                          required: true,
                          instructions: "组标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "label",
                          required: true,
                          instructions: "组件标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "value",
                          required: true,
                          instructions: "选中的值",
                          type: "string | number | boolean",
                          default: "",
                          children: [],
                        },
                        {
                          name: "segmented",
                          required: true,
                          instructions: "是否分段",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "multiple",
                          required: true,
                          instructions: "多选",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "group",
                          required: false,
                          instructions: "选项分组",
                          type: "false | undefined",
                          default: "",
                          children: [],
                        },
                        {
                          name: "options",
                          required: true,
                          instructions: "选项,T为string | number | boolean",
                          type: "T[] | {label:string;value:T;}[]",
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "SelectType.Base<T, SelectType.ConstantOption<T>, SelectType.Multiple<T>>",
                      required: false,
                      instructions: "多选基本选项",
                      type: "object",
                      default: "",
                      children: [
                        {
                          name: "type",
                          type: 'FieldType.Select | "select"',
                          required: true,
                          instructions: "组件类型",
                          default: "",
                          children: [],
                        },
                        {
                          name: "id",
                          required: false,
                          instructions: "唯一标识",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "targetGroupLabel",
                          required: true,
                          instructions: "组标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "label",
                          required: true,
                          instructions: "组件标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "value",
                          required: true,
                          instructions: "选中的值",
                          type: "string[] | number[] | boolean[]",
                          default: "",
                          children: [],
                        },
                        {
                          name: "segmented",
                          required: true,
                          instructions: "是否分段",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "multiple",
                          required: true,
                          instructions: "多选",
                          type: "true",
                          default: "",
                          children: [],
                        },
                        {
                          name: "group",
                          required: false,
                          instructions: "选项分组",
                          type: "false | undefined",
                          default: "",
                          children: [],
                        },
                        {
                          name: "options",
                          required: true,
                          instructions: "选项,T为string | number | boolean",
                          type: "T[] | {label:string;value:T;}[]",
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "SelectType.Base<T, SelectType.GroupOption<T>, SelectType.Single<T>>",
                      required: false,
                      instructions: "单选分组选项",
                      type: "object",
                      default: "",
                      children: [
                        {
                          name: "type",
                          type: 'FieldType.Select | "select"',
                          required: true,
                          instructions: "组件类型",
                          default: "",
                          children: [],
                        },
                        {
                          name: "id",
                          required: false,
                          instructions: "唯一标识",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "targetGroupLabel",
                          required: true,
                          instructions: "组标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "label",
                          required: true,
                          instructions: "组件标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "value",
                          required: true,
                          instructions: "选中的值",
                          type: "string | number | boolean",
                          default: "",
                          children: [],
                        },
                        {
                          name: "segmented",
                          required: true,
                          instructions: "是否分段",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "multiple",
                          required: true,
                          instructions: "多选",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "group",
                          required: false,
                          instructions: "选项分组",
                          type: "true",
                          default: "",
                          children: [],
                        },
                        {
                          name: "options",
                          required: true,
                          instructions: "选项,T为string | number | boolean",
                          type: `{ groupLabel: string; options: ({ label:string; value:T; }[] | T[]); }`,
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "SelectType.Base<T, SelectType.GroupOption<T>, SelectType.Multiple<T>>",
                      required: false,
                      instructions: "多选分组选项",
                      type: "object",
                      default: "",
                      children: [
                        {
                          name: "type",
                          type: 'FieldType.Select | "select"',
                          required: true,
                          instructions: "组件类型",
                          default: "",
                          children: [],
                        },
                        {
                          name: "id",
                          required: false,
                          instructions: "唯一标识",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "targetGroupLabel",
                          required: true,
                          instructions: "组标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "label",
                          required: true,
                          instructions: "组件标签",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "value",
                          required: true,
                          instructions: "选中的值",
                          type: "string[] | number[] | boolean[]",
                          default: "",
                          children: [],
                        },
                        {
                          name: "segmented",
                          required: true,
                          instructions: "是否分段",
                          type: "false",
                          default: "",
                          children: [],
                        },
                        {
                          name: "multiple",
                          required: true,
                          instructions: "多选",
                          type: "true",
                          default: "",
                          children: [],
                        },
                        {
                          name: "group",
                          required: true,
                          instructions: "选项分组",
                          type: "true",
                          default: "",
                          children: [],
                        },
                        {
                          name: "options",
                          required: true,
                          instructions: "选项,T为string | number | boolean",
                          type: `{ groupLabel: string; options: ({ label:string; value:T; }[] | T[]); }`,
                          default: "",
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: "BuildFormItem.Check",
              required: false,
              instructions: "复选框组件",
              type: "object",
              default: "",
              children: [
                {
                  name: "type",
                  type: 'FieldType.Check | "check"',
                  required: true,
                  instructions: "组件类型",
                  default: "",
                  children: [],
                },
                {
                  name: "id",
                  required: false,
                  instructions: "唯一标识",
                  type: "string",
                  default: "",
                  children: [],
                },
                {
                  name: "targetGroupLabel",
                  required: true,
                  instructions: "组标签",
                  type: "string",
                  default: "",
                  children: [],
                },
                {
                  name: "label",
                  required: true,
                  instructions: "组件标签",
                  type: "string",
                  default: "",
                  children: [],
                },
                {
                  name: "checked",
                  required: true,
                  instructions: "是否选中",
                  type: "boolean",
                  default: "",
                  children: [],
                },
              ],
            },
            {
              name: "BuildFormItem.Picker",
              required: false,
              instructions: "选择器组件",
              type: [
                "PickerItem.PTime",
                "PickerItem.PDate",
                "PickerItem.Color<T>",
              ],
              default: " ",
              children: [
                {
                  name: "PickerItem.PTime",
                  required: false,
                  instructions: "时间选择器",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Picker | "picker"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "pickerType",
                      required: true,
                      instructions: "选择器类型",
                      type: '"time"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "isRange",
                      required: false,
                      instructions: "是否支持范围选择",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "valueFormat",
                      required: false,
                      instructions: "自定义时间格式",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "时间",
                      type: [
                        "string",
                        "Date",
                        "[string, string]",
                        "[Date, Date]",
                      ],
                      default: "",
                      children: [
                        {
                          name: "string",
                          required: false,
                          instructions:
                            "指定了valueFormat且isRange为false时的类型",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "Date",
                          required: false,
                          instructions:
                            "未指定valueFormat且isRange为false时的类型",
                          type: "Date",
                          default: "",
                          children: [],
                        },
                        {
                          name: "[string, string]",
                          required: false,
                          instructions:
                            "指定了valueFormat且isRange为true时的类型",
                          type: "[string, string] | []",
                          default: "",
                          children: [],
                        },
                        {
                          name: "[Date, Date]",
                          required: false,
                          instructions:
                            "未指定valueFormat且isRange为true时的类型",
                          type: "[Date, Date] | []",
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "placeholder",
                      required: false,
                      instructions: "占位符(isRange为false时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "startPlaceholder",
                      required: false,
                      instructions: "起始值占位符(isRange为true时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "endPlaceholder",
                      required: false,
                      instructions: "结束值占位符(isRange为true时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "rangeSeparator",
                      required: false,
                      instructions: "范围符号(isRange为true时生效)",
                      type: "string",
                      default: "'~'",
                      children: [],
                    },
                    {
                      name: "clearable",
                      required: false,
                      instructions: "是否可清空",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "disabledHours",
                      required: false,
                      instructions: "禁用的小时",
                      type: "(role: string, comparingDate?: any) => number[]",
                      default: "",
                      children: [],
                    },
                    {
                      name: "disabledMinutes",
                      required: false,
                      instructions: "禁用的分钟",
                      type: "(hour: number, role: string, comparingDate?: any) => number[]",
                      default: "",
                      children: [],
                    },
                    {
                      name: "disabledSeconds",
                      required: false,
                      instructions: "禁用的秒",
                      type: "(hour: number, minute: number, role: string, comparingDate?: any) => number[]",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "PickerItem.PDate",
                  required: false,
                  instructions: "日期选择器",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Picker | "picker"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "pickerType",
                      required: true,
                      instructions: "选择器类型",
                      type: '"date"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "isRange",
                      required: false,
                      instructions: "是否支持范围选择",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "valueFormat",
                      required: false,
                      instructions: "自定义时间格式",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "时间",
                      type: [
                        "string",
                        "Date",
                        "[string, string]",
                        "[Date, Date]",
                      ],
                      default: "",
                      children: [
                        {
                          name: "string",
                          required: false,
                          instructions:
                            "指定了valueFormat且isRange为false时的类型",
                          type: "string",
                          default: "",
                          children: [],
                        },
                        {
                          name: "Date",
                          required: false,
                          instructions:
                            "未指定valueFormat且isRange为false时的类型",
                          type: "Date",
                          default: "",
                          children: [],
                        },
                        {
                          name: "[string, string]",
                          required: false,
                          instructions:
                            "指定了valueFormat且isRange为true时的类型",
                          type: "[string, string] | []",
                          default: "",
                          children: [],
                        },
                        {
                          name: "[Date, Date]",
                          required: false,
                          instructions:
                            "未指定valueFormat且isRange为true时的类型",
                          type: "[Date, Date] | []",
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "placeholder",
                      required: false,
                      instructions: "占位符(isRange为false时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "startPlaceholder",
                      required: false,
                      instructions: "起始值占位符(isRange为true时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "endPlaceholder",
                      required: false,
                      instructions: "结束值占位符(isRange为true时生效)",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "rangeSeparator",
                      required: false,
                      instructions: "范围符号(isRange为true时生效)",
                      type: "string",
                      default: "'~'",
                      children: [],
                    },
                    {
                      name: "clearable",
                      required: false,
                      instructions: "是否可清空",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                  ],
                },
                {
                  name: "PickerItem.Color<T>",
                  required: false,
                  instructions: "颜色选择器, T为boolean, true表示支持透明度",
                  type: "object",
                  default: "",
                  children: [
                    {
                      name: "type",
                      type: 'FieldType.Picker | "picker"',
                      required: true,
                      instructions: "组件类型",
                      default: "",
                      children: [],
                    },
                    {
                      name: "id",
                      required: false,
                      instructions: "唯一标识",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "targetGroupLabel",
                      required: true,
                      instructions: "组标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "label",
                      required: true,
                      instructions: "组件标签",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "pickerType",
                      required: true,
                      instructions: "选择器类型",
                      type: '"color"',
                      default: "",
                      children: [],
                    },
                    {
                      name: "value",
                      required: true,
                      instructions: "颜色值",
                      type: "string",
                      default: "",
                      children: [],
                    },
                    {
                      name: "alpha",
                      required: false,
                      instructions: "是否支持透明度",
                      type: "T",
                      default: "",
                      children: [],
                    },
                    {
                      name: "showAlpha",
                      required: false,
                      instructions: "是否显示透明度选择",
                      type: "boolean",
                      default: "",
                      children: [],
                    },
                    {
                      name: "colorFormat",
                      required: false,
                      instructions: "颜色格式",
                      type: [
                        "'hex' | 'hsl' | 'hsv' | 'rgb'",
                        `'hex' | 'hsl' | 'hsv' | 'rgb' | 'hsla' | 'hsva' | 'hexa' | 'rgba'`,
                      ],
                      default: "",
                      children: [
                        {
                          name: "'hex' | 'hsl' | 'hsv' | 'rgb'",
                          required: false,
                          instructions: "不支持透明度时的类型",
                          type: "'hex' | 'hsl' | 'hsv' | 'rgb'",
                          default: "",
                          children: [],
                        },
                        {
                          name: `'hex' | 'hsl' | 'hsv' | 'rgb' | 'hsla' | 'hsva' | 'hexa' | 'rgba'`,
                          required: false,
                          instructions: "支持透明度时的类型",
                          type: `'hex' | 'hsl' | 'hsv' | 'rgb' | 'hsla' | 'hsva' | 'hexa' | 'rgba'`,
                          default: "",
                          children: [],
                        },
                      ],
                    },
                    {
                      name: "predefine",
                      required: false,
                      instructions: "预设颜色",
                      type: "string[]",
                      default: "",
                      children: [],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  returnValue: {
    type: `void`,
  },
  example: {
    title: "构建与用户交互的表单",
    code: `buildForm([]);`,
  },
  searchKeys: ["build", "from"],
  codeSnippet: "buildForm(${1:buildFormList});${0:}",
};
