/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiDocumentItem: typeof import('./components/apiTest/ApiDocumentItem.vue')['default']
    AppSetting: typeof import('./components/AppSetting.vue')['default']
    ATHeader: typeof import('./components/apiTest/ATHeader.vue')['default']
    AutoTitleBar: typeof import('./components/AutoTitleBar.vue')['default']
    DirInput: typeof import('./components/moreInput/DirInput.vue')['default']
    DynamicsInput: typeof import('./components/moreInput/DynamicsInput.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ELDeclareDialogView: typeof import('./components/dialog/ELDeclareDialogView.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDialogView: typeof import('./components/dialog/ElDialogView.vue')['default']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgressDialogView: typeof import('./components/dialog/ElProgressDialogView.vue')['default']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileInput: typeof import('./components/moreInput/FileInput.vue')['default']
    FillApiParamDialog: typeof import('./components/FillApiParamDialog.vue')['default']
    GeneralDialog: typeof import('./components/dialog/GeneralDialog.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpCircleCloseFilled: typeof import('~icons/ep/circle-close-filled')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpNotification: typeof import('~icons/ep/notification')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSemiSelect: typeof import('~icons/ep/semi-select')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    RangeInput: typeof import('./components/moreInput/RangeInput.vue')['default']
    RectInput: typeof import('./components/moreInput/RectInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/Test.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
